/* ─────────────────────────────────────────────
 *  FileDrop — drag-and-drop / click-to-upload
 * ───────────────────────────────────────────── */

import React, { useRef, useState, useCallback } from "react";
import { useFloodActions } from "../context/FloodContext";
import { readFloodFile } from "../utils/fileLoader";
import { generateDemoData } from "../utils/demo";

interface FileDropProps {
  onLoadStart?: () => void;
  onLoadEnd?: () => void;
  onError?: (message: string) => void;
}

export function FileDrop({ onLoadStart, onLoadEnd, onError }: FileDropProps) {
  const { loadDataset } = useFloodActions();
  const inputRef = useRef<HTMLInputElement>(null);
  const [dragging, setDragging] = useState(false);

  const handleFile = useCallback(
    async (file: File) => {
      onLoadStart?.();
      try {
        const { dataset, fileSize } = await readFloodFile(file);
        loadDataset(dataset, fileSize);
      } catch (e: any) {
        onError?.(`Invalid JSON: ${e.message}`);
      } finally {
        onLoadEnd?.();
      }
    },
    [loadDataset, onLoadStart, onLoadEnd, onError],
  );

  const handleDemo = useCallback(() => {
    onLoadStart?.();
    // Defer so loading overlay can render
    requestAnimationFrame(() => {
      loadDataset(generateDemoData(), 0);
      onLoadEnd?.();
    });
  }, [loadDataset, onLoadStart, onLoadEnd]);

  return (
    <div className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-4 bg-[#0a0e17]/97">
      <div
        role="button"
        tabIndex={0}
        onClick={() => inputRef.current?.click()}
        onKeyDown={(e) => e.key === "Enter" && inputRef.current?.click()}
        onDragOver={(e) => {
          e.preventDefault();
          setDragging(true);
        }}
        onDragLeave={() => setDragging(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragging(false);
          if (e.dataTransfer.files[0]) handleFile(e.dataTransfer.files[0]);
        }}
        className={`
          w-[440px] max-w-[90vw] rounded-2xl border-2 border-dashed p-16
          text-center cursor-pointer transition-colors duration-300
          ${dragging ? "border-accent" : "border-white/15 hover:border-accent/60"}
        `}
      >
        <h2 className="font-mono text-base font-semibold text-accent mb-2">
          Flood Viewer
        </h2>
        <p className="text-sm text-dim leading-relaxed">
          Drop <b className="text-white/80">data.json</b> or{" "}
          <b className="text-white/80">.json.gz</b>
          <br />
          <small className="text-xs opacity-60">
            Generated by <code>sww_to_geojson_v2.py</code>
          </small>
        </p>

        <input
          ref={inputRef}
          type="file"
          accept=".json,.gz"
          className="hidden"
          onChange={(e) => {
            if (e.target.files?.[0]) handleFile(e.target.files[0]);
          }}
        />
      </div>

      <button
        onClick={handleDemo}
        className="
          mt-3 rounded-lg border border-white/15 bg-white/5
          px-6 py-2.5 font-semibold text-sm text-accent
          transition hover:bg-white/10 hover:border-accent/40
        "
      >
        Load demo data (synthetic)
      </button>
    </div>
  );
}
